spring:
  application:
    name: Warehouse

  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.data.jpa.repository.query: debug
